spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: Bunny@15052005
  jpa:
    show-sql: true
  server:
    tomcat:
      max-swallow-size: -1
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
websiteUrl: http://localhost:4242
file:
  upload-dir: /Users/hemanthjangam/store-uploads/