spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    show-sql: true
  server:
    tomcat:
      max-swallow-size: -1
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
websiteUrl: http://localhost:4242
file:
  upload-dir: ${FILE_UPLOAD_DIR:uploads}
