spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: Bunny@15052005
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242